<?php $meta = ['title' => 'Capacidades — OPERON', 'description' => 'Capacidades operacionais que transformam recorrência, contexto e decisão em sistemas que continuam.']; ?>
<section class="page-hero page-hero--cinematic wrap"><p class="kicker">Capacidades OPERON</p><h1>Não entregamos tarefas.<br>Construímos o que passa a <em>saber fazê-las.</em></h1><p class="page-hero__lead">Estruturamos trabalhos recorrentes para que contexto, critérios e memória acompanhem a operação — sem tudo precisar voltar à mesma pessoa.</p><canvas class="page-hero__word" data-fx="vapor" data-words="Vendas|Operação|Memória|Decisão" aria-hidden="true"></canvas></section>
<section class="capability-list wrap">
<?php foreach ([
['01','Capacidade comercial','Propostas nascem com histórico, critérios, limites e memória — prontas para a revisão certa.','Da solicitação à proposta','Toda proposta começa do zero ou espera alguém definir preço.','Mais consistência, rastreabilidade e velocidade para revisar.','commercial','Mensagens e critérios dispersos convergem em uma proposta consistente.'],
['02','Capacidade de atendimento','Cada conversa começa com contexto e termina alimentando a próxima ação.','Da pergunta à continuidade','O cliente repete informações e o próximo atendimento não sabe o que aconteceu.','Continuidade entre canais, pessoas e próximas ações.','service','Conversas dispersas convergem em uma linha contínua de contexto.'],
['03','Capacidade de gestão','Sinais dispersos viram leitura operacional, responsáveis e decisões rastreáveis.','Do ruído à direção','Planilhas mostram partes, mas ninguém enxerga onde o trabalho realmente para.','Gargalos visíveis, responsáveis claros e exceções direcionadas.','management','Sinais operacionais ganham direção, rota e responsabilidade.'],
['04','Capacidade de conhecimento','O que a empresa aprende deixa de desaparecer em pessoas, chats e arquivos.','Da experiência à memória','A mesma dúvida retorna e decisões antigas precisam ser reconstruídas.','Memória utilizável no próximo ciclo, não apenas arquivada.','memory','Experiências e decisões formam memória consultável.'],
] as [$n,$title,$copy,$shift,$symptom,$outcome,$visual,$alt]): ?>
<article class="capability-row capability-row--<?= $visual ?> reveal"><figure class="capability-visual"><img src="/assets/images/generated-v4/capability-<?= $visual ?>.webp" alt="<?= $alt ?>" width="1600" height="900" loading="lazy"></figure><span><?= $n ?></span><div><p><?= $shift ?></p><h2><?= $title ?></h2></div><div class="capability-proof"><p><b>Quando trava</b><?= $symptom ?></p><p><b>O que muda</b><?= $outcome ?></p></div><p><?= $copy ?></p><i aria-hidden="true"></i></article>
<?php endforeach; ?>
</section>
<section class="connection-system section wrap"><p class="kicker">O que uma capacidade conecta</p><h2>Não é uma automação isolada.<br><em>É um sistema legível.</em></h2><div class="connection-system__grid"><?php foreach (['Contexto','Critérios','Fluxo','Ferramentas','Memória','Revisão humana'] as $i => $item): ?><span><b>0<?= $i + 1 ?></b><?= $item ?></span><?php endforeach; ?></div></section>
<section class="page-film page-film--capabilities"><img src="/assets/images/generated-v4/capability-infrastructure.webp" alt="Cinco capacidades operacionais convergem em uma infraestrutura conectada" width="1600" height="900" loading="lazy"><div><p class="kicker">Uma nova infraestrutura</p><h2>O trabalho deixa de voltar.<br><em>Começa a continuar.</em></h2><a class="button button--light" href="/diagnostico">Descobrir qual capacidade destrava minha operação</a><small class="cta-assurance">Começamos pelo nó com maior dependência — não por uma transformação genérica.</small></div></section>
