<?php $meta = ['title' => 'Método — OPERON', 'description' => 'Como a OPERON encontra dependências, estrutura conhecimento e implanta capacidade operacional.']; ?>
<section class="page-hero page-hero--cinematic wrap"><p class="kicker">Método OPERON</p><h1>Antes de automatizar,<br>a gente faz a operação <em>se revelar.</em></h1><p class="page-hero__lead">Partimos do trabalho real, preservamos o que já funciona e introduzimos tecnologia apenas onde ela aumenta capacidade.</p><canvas class="page-hero__word" data-fx="vapor" data-words="Revelar|Estruturar|Aplicar|Evoluir" aria-hidden="true"></canvas></section>
<section class="method-story">
<?php foreach ([
 ['01','reveal','Lupa de nanopartículas sobre um fluxo e seu ponto de bloqueio.','Revelar','Observamos onde o trabalho para, quem destrava, o que se perde e quais decisões retornam.','Saída: mapa do nó, dependências e recorrências.'],
 ['02','structure','Arquivos e decisões encontrando uma estrutura comum.','Estruturar','Transformamos conhecimento implícito em contexto, processo, critério, responsabilidade e limite.','Saída: lógica operacional que pessoas conseguem ler e revisar.'],
 ['03','apply','Ferramentas, decisão humana e automação em um único fluxo.','Aplicar','Conectamos as ferramentas certas ao sistema desenhado — aproveitando o que já existe antes de introduzir o novo.','Saída: fluxo funcional com automação e revisão nos lugares certos.'],
 ['04','evolve','Ciclo de sinais e memória que retroalimenta a operação.','Evoluir','Medimos sinais, revisamos exceções e ampliamos somente a capacidade que provou funcionar.','Saída: memória, indicadores e uma próxima decisão informada.'],
] as [$n,$visual,$alt,$title,$copy,$output]): ?><article class="method-story__step wrap reveal"><figure class="method-visual"><img src="/assets/images/generated-v5/method-<?= $visual ?>.webp" alt="<?= $alt ?>" width="560" height="315" loading="lazy"></figure><span><?= $n ?></span><h2><?= $title ?></h2><div><p><?= $copy ?></p><strong><?= $output ?></strong></div></article><?php endforeach; ?>
</section>
<section class="method-deliverables section wrap"><p class="kicker">O que ganha forma</p><h2>Da leitura do problema<br><em>à capacidade observável.</em></h2><div><?php foreach ([['Mapa','Onde a operação para e por quê.'],['Critérios','Como a decisão deve acontecer.'],['Fluxo','Quem ou o que age em cada etapa.'],['Sinais','Como saber se a capacidade funciona.']] as $i => [$title,$copy]): ?><article><span>0<?= $i + 1 ?></span><h3><?= $title ?></h3><p><?= $copy ?></p></article><?php endforeach; ?></div></section>
<section class="page-film page-film--method"><img src="/assets/images/generated-v5/method-node.webp" alt="Operação caótica que encontra um nó de decisão e se transforma em fluxo claro" width="560" height="315" loading="lazy"><div><p class="kicker">Tecnologia entra no lugar certo</p><h2>Não começa pela ferramenta.<br><em>Começa pelo nó.</em></h2><a class="button button--light" href="/diagnostico">Conversar sobre o nó da minha operação</a><small class="cta-assurance">Analisamos o contexto antes de recomendar qualquer tecnologia.</small></div></section>
