<?php $meta = ['title' => 'Sobre — OPERON', 'description' => 'As pessoas por trás da OPERON: estratégia, tecnologia e realidade operacional para empresas operarem além do improviso.']; ?>
<section class="page-hero page-hero--about wrap"><p class="kicker">Sobre a OPERON</p><h1>Capacidade não nasce de ferramenta.<br><em>Nasce de gente que entende o trabalho.</em></h1><p class="page-hero__lead">A OPERON junta visão operacional, lógica comercial, tecnologia, IA, automação e linguagem para transformar conhecimento disperso em uma rotina que continua funcionando.</p><canvas class="about-hero__field" data-fx="morph" data-shapes="rede|orbita|camadas" data-hold="4200" aria-hidden="true"></canvas></section>
<section class="operon-thesis section"><div class="wrap reveal"><p class="kicker">Por que a OPERON existe</p><h2>Empresa nenhuma deveria depender de uma pessoa para <em>lembrar, decidir ou destravar</em> o que precisa continuar.</h2><p>Quando contexto, critérios e memória ganham forma, tecnologia deixa de ser uma coleção de ferramentas e passa a ampliar a capacidade de quem faz a empresa acontecer.</p></div></section>
<section class="about-origin section wrap"><div class="about-origin__copy reveal"><p class="kicker">O ponto de partida</p><h2>O trabalho real é mais inteligente do que o processo que ficou no papel.</h2><p>É por isso que a gente começa ouvindo a operação: o que volta, o que depende de alguém, onde a decisão perde contexto e qual nó vale destravar primeiro.</p></div><div class="about-origin__signal reveal"><canvas data-fx="morph" data-shapes="ruido|rede|seta" data-hold="3600" aria-hidden="true"></canvas><p><b>Não entregamos automação solta.</b> Construímos uma capacidade que a equipe consegue usar, questionar e evoluir.</p></div></section>
<section class="founders founders--portrait wrap" aria-labelledby="founders-title"><div class="founders__heading reveal"><p class="kicker">Quem dá direção</p><h2 id="founders-title">Duas leituras.<br><em>Uma operação que continua.</em></h2></div>
<?php foreach ([
 ['Yohann Escher','Estratégia, sistemas e expressão.','Desenha a próxima capacidade e conecta código, inteligência artificial, processos e linguagem em experiências operacionais legíveis.',['Arquitetura de capacidade','IA, automação e produto','Identidade e comunicação'],'about-yohann-hq.webp','Retrato de Yohann Escher em meio a nanopartículas'],
 ['Matheus Marques','Operação, relação e crescimento.','Faz a capacidade encontrar a realidade: pessoas, decisões, processos, clientes e crescimento sustentável.',['Leitura operacional','Lógica comercial','Adoção e evolução'],'about-matheus-hq.webp','Retrato de Matheus Marques em meio a nanopartículas'],
] as [$name,$title,$copy,$points,$image,$alt]): ?><article class="founder-card reveal"><figure class="founder-portrait"><img src="/assets/images/about/<?= $image ?>" alt="<?= $alt ?>" width="1200" height="675" loading="lazy"></figure><div class="founder-card__copy"><span><?= $name ?></span><h3><?= $title ?></h3><p><?= $copy ?></p><ul><?php foreach ($points as $point): ?><li><?= $point ?></li><?php endforeach; ?></ul></div></article><?php endforeach; ?></section>
<section class="team-constellation section"><div class="wrap"><div class="team-constellation__head reveal"><p class="kicker">A equipe em volta da operação</p><h2>Direção não acontece sozinha.<br><em>Ela ganha escala em conjunto.</em></h2><p>Além dos fundadores, a OPERON conta com uma equipe que transforma estratégia em experiência, estrutura e ritmo de entrega.</p></div><div class="team-constellation__system reveal"><canvas data-fx="morph" data-shapes="rede|orbita|blocos" data-hold="4000" aria-hidden="true"></canvas><div class="team-constellation__names" aria-label="Equipe OPERON"><?php foreach (['Elisa','Evandro','Samuel','Vitor'] as $i => $name): ?><article><span>0<?= $i + 1 ?></span><strong><?= $name ?></strong><small>Equipe OPERON</small></article><?php endforeach; ?></div></div></div></section>
<section class="principles section wrap"><p class="kicker">Como escolhemos construir</p><div><?php foreach ([['Direção humana','Responsabilidade e futuro continuam com pessoas.'],['Tecnologia em contexto','Ferramentas entram depois que a operação faz sentido.'],['Legibilidade','O sistema precisa ser entendido por quem o utiliza.'],['Evolução observável','Só ampliamos o que demonstra capacidade.']] as $i => [$title,$copy]): ?><article class="reveal"><span>0<?= $i + 1 ?></span><h3><?= $title ?></h3><p><?= $copy ?></p></article><?php endforeach; ?></div><a class="button button--light" href="/diagnostico">Conversar sobre minha dependência operacional</a></section>
